* Zeolite Simulation Environment
Author: Jerry Crum \\
Updated: 1/12/2021

* Description
This is a package for automating structure generation and characterization of zeolites for computational chemistry.

* Requirements
This package is built around the ASE atoms object, and thus requires installation of ASE, available at: https://wiki.fysik.dtu.dk/ase/install.html.

Ring finding uses graph theory implemented by NetworkX, available at: https://networkx.github.io.

Numpy is also required.

* Installation

Clone this git repository into your PYTHONPATH (i.e. anaconda3/lib/python3.X/site-packages/), and you are good to go. Also, you can clone this git repository anywhere you want, and then add the location to your PYTHONPATH.

* Current Modules
To see how to use each of the modules, please visit [[/examples][examples]].
- zse.cation
- zse.collections
- zse.protonate
- zse.rings
- zse.substitute
- zse.utilities
* Contributions

If there is something you would like to see added to this package, or if you would like to contribute, please email me at jcrum@nd.edu.

* Acknowledgments
** Contributors

Jerry Crum, Justin Crum, Sichi Li, Yujia Wang, William Schneider

** Testers

Craig Waitt, Jian Ren Lim, Elsa Koninckz
